### ISSUE TITLE
Error with two open boundries

### ISSUE THREAD

**Issue by aahgohoxij** [schism-dev/schism#106]
Hello,
When I set up two open boundaries and land boundaries in xmgredit5 and run the model, I encounter the following error:

"At line 2380 of file Hydro/schism_init.F90 (unit = 31, file = 'bctides.in')
Fortran runtime error: Bad integer for item 1 in list input."

I have tried modifying the bctides.in file and it doesn't work, what should I do when I set  two open boundaries and land boundaries?

Thanks all.

**Comment by josephzhang8** [comment]
Please ask generic questions via SCHISM mailing list. This place is reserved for code issues.

You can find answers in the user manual: https://schism-dev.github.io/schism/master/input-output/bctides.html
