### ISSUE TITLE
Compile GOTM 3.2.5

### ISSUE THREAD

**Issue by hb-9797** [schism-dev/schism#127]
Hi all:
I followed the "readme(inside GOTM/)" to install the GOTM library. When I go into the "src" folder and use "make realclean "and "make", I get the following error already:
"/data/hb/schism-5.11.0/src/GOTM3.2.5/compilers/compiler.: No such file or directory
make: *** No rule to make target `/data/hb/schism-5.11.0/src/GOTM3.2.5/compilers/compiler.'.  Stop", 
no relevant files found. I was able to run schism successfully without using the GOTM module before. Here are the environment variables as well as the error screenshot:
![image](https://github.com/schism-dev/schism/assets/129708252/34164927-55f0-4b44-bc9d-6e6d22e1d628)
![image](https://github.com/schism-dev/schism/assets/129708252/56cd9698-9c72-438e-9827-e2a9cac19a4d)

**Comment by josephzhang8** [comment]
For GOTM, please use cmake.




-Joseph



Joseph Zhang

Office: (804) 684 7466

Web: schism.wiki



________________________________
From: Bo Huang ***@***.***>
Sent: Friday, February 23, 2024 11:17 AM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] Compile GOTM 3.2.5 (Issue #127)


[EXTERNAL to VIMS received message]


Hi all:
I followed the "readme(inside GOTM/)" to install the GOTM library. When I go into the "src" folder and use "make realclean "and "make", I get the following error already:
"/data/hb/schism-5.11.0/src/GOTM3.2.5/compilers/compiler.: No such file or directory
make: *** No rule to make target `/data/hb/schism-5.11.0/src/GOTM3.2.5/compilers/compiler.'. Stop",
no relevant files found. I was able to run schism successfully without using the GOTM module before. Here are the environment variables as well as the error screenshot:
image.png (view on web)<https://github.com/schism-dev/schism/assets/129708252/34164927-55f0-4b44-bc9d-6e6d22e1d628>
image.png (view on web)<https://github.com/schism-dev/schism/assets/129708252/56cd9698-9c72-438e-9827-e2a9cac19a4d>
