### ISSUE TITLE
Install with conda

### ISSUE THREAD

**Issue by brey** [schism-dev/schism#13]
Dear All, may I suggest to configure also a conda based installation option, preferably on conda-forge. One can have multiple builds to meet all the configurations of SCHISM. 

I think this option will provide a flexible and portable way to use SCHISM. 

I have played a bit with this and I have managed to have it up and running relatively easy. You can try it out with 

`conda install -c gbrey pschism`

It works for linux-64 and os-x. 

Let me know if I could be of any help.

George

**Comment by platipodium** [comment]
I would like a `conda install` possibility, but be aware that conda is not recommended on HPC systems (we recently removed it from ours), see e.g. https://docs.computecanada.ca/wiki/Anaconda/en.  

Also, with the current strategy of most dependencies resolved in-tree, the dependency management is not (yet) too complicated (mostly netcdf).  This could become a more pressing issue if we get Joseph to accept more relying on external dependencies .. :=).

**Comment by josephzhang8** [comment]
I think George B. also mentioned the possibility of conda install.

Too bad conda is now blacklisted as we are moving in that direction.

**Comment by jreniel** [comment]
Not being able to use conda is inconvenient, but not a game changer, as you are still allowed to use virtualenv. The main difference would be that with with virtualenv you might need to satisfy some dependencies manually,  something that we still have to do anyways when we provision a machine with the SCHISM binaries.

**Comment by josephzhang8** [comment]
Good to know; thx Jaime.

**Comment by brey** [comment]
Dear All, I do agree that for a production HPC env it would make sense to have a module based installation for efficiency but, in my opinion, for development and prototyping nothing beats the simplicity of conda. Having the same configuration on the HPC and my laptop (where the dev is happening) within minutes without the need of Admin rights is very productive. I am using conda on our HPC since I couldn't get SCHISM compiled with the available modules and I am only doing test runs anyway. Your mileage may vary. The above referenced conda command installs the 4.8 tagged version and works for me (let me know if you have any problems). It would take some efforts to have all options configured though. I have compiled mine with mpich but we need to have one with OpenMP as well. Not to mention all the variants of SCHISM modules.  I will make a pull request with the conda recipe files asap.

**Comment by brey** [comment]
I am working in finalising the conda recipe. May I reiterate the possibility of having the metis/parmetis dependency covered independently from a stand alone installation. 

Both packages are available in conda. 

Any reason why they need to be included in the build process?

**Comment by josephzhang8** [comment]
Hi Geroge:

PM3 used to have an issue so we had to use our own copy. PM4 can be used out-of-box without any modifications. So I think it's ok to link to a pre-installed PM4 lib. Thx.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by brey** [comment]
In that case, any ideas on how to mask the compilation of the local Metis folder from `CMake` (not my strong point)?

**Comment by josephzhang8** [comment]
Hi Eli:

Could you add that in cmake also, since you are the original architect? Thx.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by jreniel** [comment]
Not my strong point either, but my intuition tells me that you probably still need the parmetis headers to compile schism, and of course, they have to match whatever binary version is being bootstrapped through conda. Since you still need the parmetis headers, and since the parmetris source code is bundled inside the schism source code, doing full parmetis compilation might actually be better than using a conda one. In any case, it's your choice, it depends how much you want to leverage "flexibility" against complexity.

In any case, I think it might be possible to bootstrap the conda metis lib, as long as the headers used match versions (I'm not sure if conda will distribute the headers along with the binaries though, which would technically be the safest route). I would just compile the provided metis as part of the schism-conda recipe, but that's just me...

**Comment by jreniel** [comment]
FYI, if you want to deploy SCHISM anywhere and make sure it uses with `modules` then you can use any of these links:

[https://github.com/jreniel/schism_deploy_v5.8.0](https://github.com/jreniel/schism_deploy_v5.8.0)
[https://github.com/jreniel/schism_deploy_master](https://github.com/jreniel/schism_deploy_v5.9.0)
[https://github.com/jreniel/schism_deploy_master](https://github.com/jreniel/schism_deploy_master)

**Comment by josephzhang8** [comment]
Sure. Again it will be next week before I have even a hope. To clarify (I'm a bit asleep during this exchange) is the subject of this to compile parmetis and not metis or is the subject to drop the whole library.

One thing we discussed in the burst of activity around moving to GitHub was the possibility of automatically downloading parmetis if its location isn't named.  I believe this required a version bump. I guess it isn't a very powerful idea though while the library is housed inside the schism source code.
________________________________
From: Y. Joseph Zhang ***@***.***>
Sent: Friday, November 12, 2021 7:21 AM
To: schism-dev/schism ***@***.***>; schism-dev/schism ***@***.***>
Cc: Comment ***@***.***>; Ateljevich, ***@***.*** ***@***.***>
Subject: RE: [schism-dev/schism] Install with conda (#13)


Hi Eli:



Could you add that in cmake also, since you are the original architect? Thx.





-Joseph



Joseph Zhang

Office: (804) 684 7466

Web: schism.wiki

**Comment by jreniel** [comment]
> is the subject of this to compile parmetis and not metis or is the subject to drop the whole library.
The subject is whether the conda recipe should use the precompiled version that exists in the conda repo, or should it compile the one included with SCHISM. Technically you can do either, the question is what you gain and lose from chose one or the other. I don't think dropping the whole library is part of the conversation (I don't think that's even possible, since parmetis obviosuly plays a critical role!)

Easy and safe is to compiled the one bundled. Using the conda one would probably require to find and match the correct version of the headers, so while doable, might be more complicated than simply compiling the one provided.

> One thing we discussed in the burst of activity around moving to GitHub was the possibility of automatically downloading parmetis if its location isn't named. I believe this required a version bump. I guess it isn't a very powerful idea though while the library is housed inside the schism source code.

I remember these conversations, and while we flirted with the idea of downloading on the fly, I now with more experience think it is better to just keep it in the source code (for simplicity). But there are other formal alternatives, most notably git subtrees, which I would suggest to talk about in the event that we need to change the Parmetis version in the future.

**Comment by josephzhang8** [comment]
Thx Eli for your help. I just want to add that compiling PM each  time takes trivial amount of time, so as an average user I'd always do that. This also avoided any dependency. I do understand George's point of linking to an existing PM lib though.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by jreniel** [comment]
FYI This isn't Eli talking. He hasn't actually responded. Eli probably knows by memory which CMake variables need to be overridden for using conda parmetis. I would have to dig a little to find them, but through CMake variables you certainly can override which Parmetis gets used.

**Comment by brey** [comment]
Hi All. I have sorted out the issues with CMAKE and METIS/PARMETIS. The conda recipe avoids compiling the local library and uses the `conda-forge` version. 

You can get both `pschism` and `pschism-wwm` with 

`conda install -c gbrey pschism=5.9`

or 

`conda install -c gbrey pschism-wwm=5.9`


However, I am having an issue with the `wwm` flavor on Linux (it compiles nicely on osx). I have traced the problem to the definition of constants in OPENMP. See https://stackoverflow.com/questions/63016641/cant-support-both-openmp-v4-and-v5-in-gcc.

Apparently such an issue doesn't affect clang that is why it works on osx. Let me know if you've seen this issue and how, in your opinion, should be addressed.

**Comment by platipodium** [comment]
Thanks for the update.  I think that we should deprecate the use of gcc < 9 / OpenMP < 5.  The current stable version is 11, with version 12 expected in April 2021.

**Comment by jamal919** [comment]
> However, I am having an issue with the `wwm` flavor on Linux (it compiles nicely on osx). I have traced the problem to the definition of constants in OPENMP. See https://stackoverflow.com/questions/63016641/cant-support-both-openmp-v4-and-v5-in-gcc.

Do you think #57 relates to this problem?

**Comment by platipodium** [comment]
@gbrey what is the status of the conda deployment?

**Comment by brey** [comment]
@platipodium I think it's done. I was wondering if there is a need to have the OLD IO option even with >5.10 but I think that having the 5.9 version should be enough. You can test both versions on my channel with 

```python
conda install -c gbrey pschism=5.10*=mpi_openmpi*
conda install -c gbrey pschism=5.10*=mpi_mpich*
conda install -c gbrey pschism=5.9*=mpi_openmpi*
conda install -c gbrey pschism=5.9*=mpi_mpich*
```

and 

```python
conda install -c gbrey pschism-wwm=5.10*=mpi_openmpi*
conda install -c gbrey pschism-wwm=5.10*=mpi_mpich*
conda install -c gbrey pschism-wwm=5.9*=mpi_openmpi*
conda install -c gbrey pschism-wwm=5.9*=mpi_mpich*
```


depending on your MPI flavour. I will do a last check and then I will push a PL to the repo and also one in the `conda-forge`  channel if no one has an objection.

In fact someone should also be admin/maintainer on `conda-forge` besides me. Any volunteers?

**Comment by platipodium** [comment]
@gbrey Thanks for the update.  

 * Yes, I think you should submit to conda-forge.  
 * If needed, I can be a secondary maintainer. 
 * Yes, we need OLDIO for all versions, as we need single-processor capability.  (I know you can circumvent this with `--oversubscribe`, but that is *much* slower)

**Comment by josephzhang8** [comment]
Thank you George, Carsten.


Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)

SCHISM web: http://ccrm.vims.edu/schism/

**Comment by brey** [comment]
@platipodium Keeping the OLDIO option creates a problem.

Currently there are 2 binaries (TVD-LD and WWM) and 2 MPI options (`mpich` and `openmpi`). Thus the 4 total versions/release above. However, if we include the OLDIO as an option it would create 8 versions and most importantly a naming issue. How are we going to call the OLDIO packages?

```python
pschism, pschism-oldio
pschism-wwm, pschism-wwm-oldio
``` 

This will create some confusion. Is running on one core a long term requirement?

In fact, this is relevant to a more general question: How many conda versions we want to release (in terms of modules)? If there are many, the OLDIO option will increase the number. Ideally, the best option would be to have one binary and invoke the modules in runtime. Is this doable?

Also, maybe there is a way to speed up `--oversubscribe`.

**Comment by josephzhang8** [comment]
HI George:

Invoking modules at runtime is not possible; most modules use their own 'private' arrays for memory conservation. There are other considerations as well (e.g. TVD for efficiency).


Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)

SCHISM web: http://ccrm.vims.edu/schism/

**Comment by brey** [comment]
Thanks Joseph. How about using only OpenMP and multithreading for running on one core without oversubscribing?

**Comment by platipodium** [comment]
1) Hmm, I think we need to find a way to deal with multiple options. OLDIO is only one of them, WWM, TVD-VL, FABM, GEN and any of the others could also be relevant.  In principle conda should be able to handle this, but I am no expert on the variants.  

There could be a default variant
pschism (using openmpi, OLDIO=OFF and TVD-VL=SB, or any other)

And then many variants with positive selection in any way conceivable....
pschism+FABM+OLDIO+WWM+SB
pschism+VL+WWM+GEN+ICM+MPICH

We can use CD to create all of them and the respective conda packages.

2) Not providing MPI (in both flavours openmpi/mpich) would deter users who need that capability, not offering single-processor options would deter first-timers or people who'd like to try the system or who have simple test cases.

**Comment by josephzhang8** [comment]
I assume you mean hyperthreading? This is possible as long as the system allows it, either under openMP or MPI or both. Our experience is that HT with openMP works best. You can run with 1 core and openMP threads also.


Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)
SCHISM web: http://ccrm.vims.edu/schism/

**Comment by brey** [comment]
```
not offering single-processor options would deter first-timers or people who'd like to try the system or who have simple test cases.
```

I am not sure I get this. Every computer now is multicore. So testing the code on a simple case, even with MPI, and at minimum 2 cores shouldn't be a problem. If you output a large number of vectors this could be an issue for, say, an 8 core laptop but this gets very specific.

Note that coda installation is good enough for prototyping but not necessarily for production (side note, @pmav99 achieved extremely good latency with a `conda` implementation on Azure HPC with `InfiniBand`) .

In addition, `conda` provides automatically the `MPI` without any issues for the user. I remember you've mentioned multiple 1 core experiments with `FABM`. Those become now 2+ cores experiments which is an issue but I would say poses no big constraint for a new user testing stuff. It would, however, require more resources for scaling up. 

Did I miss something?

Another option would be to update the code on the `5.9` branch differentiating between OLDIO and the new one on the semantic versioning. I am not sure though if this is the right approach going forward.

**Comment by josephzhang8** [comment]
Issue resolved per @brey

**Comment by platipodium** [comment]
Hmm, I see how this could be very confusing for users who want to "Just download SCHISM".  How about providing those that we (whoever) frequently use.  My personal list is as matrix of all combinations of [SB, OLDIO, FABM, GEN]

**Comment by josephzhang8** [comment]
Q1. What are the options for TVD_LIM? I am bit confused with OS.

>> This flag sets the TVD schemes. OS stands for 'Osher' scheme. We typically used VL.

Q2. Are all module options compatible between them? That is, do all possible combinations of SED2, WWM & ICE work and therefore should be offered?

Q4. Same as Q2 for PH, COSINE, FIB, SED (different from SED2?) and FABM.

>> Most modules are orthogonal to each other, so mix-and-match is fine, but some combinations may not make sense.

Exceptions: (1) SED2D is kinda obsolete with polymorphism and SED (3D sediment transport module), and may be removed in the future; (2) PH is a sub-module of ICM only.

Q3. Should there be only one tracer model available per binary or more tracer modules can be present?
>> Normally, yes but sometimes it makes sense to have more, e.g. GEN+AGE+ICM+SED is used in our project. FABM is supposed to be the most flexible that would ultimately replace all BGC modules, but this is on-going work.

It's up to you how many combinations you want to offer with conda. It's hard to define 'popular' combinations as the community is diverse. Thx.

Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)
SCHISM web: http://ccrm.vims.edu/schism/

**Comment by brey** [comment]
I have pushed the final `conda` recipe. It includes instructions on how to build ones own package. At this point, I think it's better if the interested users build their own package with their own configuration. If the complexity of the modules/models improves or a way to initiate them in run time is developed we can consider `conda-forge`. 

I don't believe there is a graceful way to build all the variants in `conda-forge` currently. Maybe also `conda` will offer some new ways going forward.

**Comment by platipodium** [comment]
Out of curiosity, how do you provide your own channel `-c gbrey` ?

**Comment by brey** [comment]
https://docs.anaconda.com/anacondaorg/user-guide/tasks/work-with-packages/#uploading-packages
