### ISSUE TITLE
set_mask error during compilation of SCHISM-FABMv2-(ECOSMO)

### ISSUE THREAD

**Issue by jpein1** [schism-dev/schism#133]
When doing "make pschism" with FABM v2 module enabled in mk/include_modules, I get the following error: 

mpiifort -c  -DMPIVERSION=2  -DSCHISM -DPREC_EVAP -DTVD_VL -DUSE_FABM -xCORE-AVX2 -O2 -assume byterecl -heap-arrays -traceback   -I./Fabm/build/include  -module o/svn.STRAND_Apr2024_intel19 -Io/svn.STRAND_Apr2024_intel19  -I/project/opt/software/netcdf/4.7.0/intel/include  Fabm/fabm_schism.F90 -o o/svn.STRAND_Apr2024_intel19/fabm_schism.o
Fabm/fabm_schism.F90(389): error #6460: This is not a field name that is defined in the encompassing structure.   [SET_MASK]
  call fs%model%set_mask(fs%mask, fs%mask_hz)

In fact both option in the following statement do not work during compilation:

#if _FABM_API_VERSION_ < 1
  call fabm_set_mask(fs%model, fs%mask, fs%mask_hz)
#else
  call fs%model%set_mask(fs%mask, fs%mask_hz)
#endif

Question: Is the "set mask" function needed at all in SCHISM? If yes, how to formulate correctly when using FABM v2?

**Comment by platipodium** [comment]
Thanks for reporting this.  I have not been able to reproduce the problem, but I'll try with the makefile you provided. 

In general, I found the use of set_mask much more consistent than internal hacks employing constructs like ` foreach value in array[i,k,n] if value = NaN then cycle`.  Using a 2d mask makes this much more efficient.

**Comment by platipodium** [comment]
I also noticed that the `fabm_driver.h` has not been merged upstream yet.  

So to define the mask, you need to add the file:

```
echo << EOT >  $FABM_BASE/src/drivers/schism/fabm_driver.h
! Copyright 2017 Helmholtz-Zentrum Geesthacht
! Licensed under the Apache License, Version 2.0
!  (http://www.apache.org/licenses/LICENSE-2.0)
! Author(s): Richard Hofmeister

#define _FABM_DIMENSION_COUNT_ 2
#define _FABM_DEPTH_DIMENSION_INDEX_ 1
#define _FABM_VECTORIZED_DIMENSION_INDEX_ 1

#define _FABM_VERTICAL_BOTTOM_TO_SURFACE_
#define _FABM_BOTTOM_INDEX_ -1

#define _FABM_MASK_TYPE_ integer
#define _FABM_MASKED_VALUE_ 1

#include "fabm.h"

EOT
```

**Comment by platipodium** [comment]
So this problem might be related to the missing `fabm_driver.h`.  Please report if adding the driver fixes the problem.  I will then merge it upstream.

**Comment by jpein1** [comment]
Thanks! After adding these lines

#define _FABM_MASK_TYPE_ integer
#define _FABM_MASKED_VALUE_ 1

to fabm_driver.h (of FABM) compilation works.

**Comment by platipodium** [comment]
Thanks for reporting, closing this as fixed

**Comment by platipodium** [comment]
I filed a PR on official fabm repo to include these lines upstream https://github.com/fabm-model/fabm/pull/64
