### ISSUE TITLE
mandatory variables in sflux

### ISSUE THREAD

**Issue by brey** [schism-dev/schism#16]
Hi All. I would like to ask if there is a way to avoid including the spfh & stmp variables in sflux. When doing only storm surge simulations these are not needed but I include them with zero values increasing however the size of the meteo forcing files. This becomes an issue for large domains. Maybe there is a parameter that controls this dependency.

**Comment by huyquangt** [comment]
There is an option NWS =5, see simpler_wind.F90. You only need UV,P.  Ivica may help with.

**Comment by brey** [comment]
If I understood correctly that means changing the name of the meteo input file and also interpolating in advance the meteo data to the grid. I did try just setting NWS to 5 and the meteo in sflux was ignored. I would like to avoid doing the interpolation as a pre-process. I would assume an option that just sets spfh and stmp to zero in the code when the variable are not present on the sflux file should not be difficult to incorporate.
