### ISSUE TITLE
leftover comma

### ISSUE THREAD

**Issue by jbclements** [schism-dev/schism#46]
https://github.com/schism-dev/schism/blob/cd8341e8f01aacb866aa44e302f1f748a3ac7a68/mk/Make.defs.ubuntu.gnu.ompi#L43

There definitely should not be a comma after openmpi-bin in this apt-get install command....

**Comment by jbclements** [comment]
Good to hear from you.

I did install the libnetcdff-dev library, as suggested several lines later. I was also slightly queasy about the fact that nothing past 18.04 was mentioned.

The docs suggest that one can build using either make or cmake; I attempted the make using just plain make. The ParMetis build halted though, indicating that cmake was required (and also g++, but who’s counting). The build then… succeeded? but … it appears that the final makefile target is libschism.a. 

I’m getting the sense that it was a mistake to try building from the first set of build instructions (the ones using make), and that I should simply have skipped that and gone straight to cmake.

If that succeeds, I can make a pull request, but it seems like the right pull request might just be to rip out the mk directory entirely, and trim the docs to instruct people to go straight for cmake.

Thanks for your response!

John Clements

**Comment by platipodium** [comment]
@jbclements please remove the references to NetCDF, this should be auto configured by CMake,  what in the end remains is merely

```
set(CMAKE_Fortran_COMPILER gfortran CACHE PATH "Path to serial Fortran compiler")
set(CMAKE_C_COMPILER gcc CACHE PATH "Path to serial C compiler")
set(CMAKE_Fortran_FLAGS_RELEASE "-O2 -ffree-line-length-none -static-libgfortran -finit-local-zero" CACHE STRING "Fortran flags" FORCE)
```

 which to me seems pretty generic for any `gnu` system.   What is specific to Ubuntu is the enumeration of needed packages (different between distros and package managers).  Also, the `update-alternatives` mechanism to select the MPI to be used.

**Comment by jbclements** [comment]
Sure enough, my instructions for ubuntu install were incomplete.

```

What follows is what appears to me to be a complete set of steps, but
I haven't run these on a totally fresh install of Ubuntu, so it's concievable
that I've missed one or more packages that are required. Edits welcome!


* Start with fresh Ubuntu 20.04.

* First, install a bunch of packages:

> sudo apt install gcc g++ gfortran netcdf openmpi-bin libnetcdf-dev libopenmpi-dev openmpi-bin python2

* Next, the world has moved on and python 2 is no longer standard; the "update-alternatives"
  utility can create a link that causes python to invoke python v2.7:

> sudo update-alternatives --install /usr/local/bin/python python /usr/bin/python2 20

* Now, check out the schism repo:

> cd ~
> git clone https://github.com/schism-dev/schism.git
> cd schism/
> git checkout tags/v5.9.0
> cd cmake

* create a file in the cmake directory called SCHISM.build.ubuntu, containing this text:

* * *
set(CMAKE_Fortran_COMPILER gfortran CACHE PATH "Path to serial Fortran compiler")
set(CMAKE_C_COMPILER gcc CACHE PATH "Path to serial C compiler")
set(CMAKE_Fortran_FLAGS_RELEASE "-O2 -ffree-line-length-none -static-libgfortran -finit-local-zero" CACHE STRING "Fortran flags" FORCE)
* * *

(Don't put the asterisks in there, those are just there to demarcate the
beginning and end of the file.)

(NB if my pull request is accepted upstream, this file may become
built-in.)

* Finally, run cmake and make:

> cd ~/schism/
> mkdir build
> cd build
> cmake -C ../cmake/SCHISM.local.build -C ../cmake/SCHISM.local.ubuntu ../src/
> make pschism

After this, the binary (just called pschism, I believe) should appear in
the bin/ subdirectory, and the libraries in ... another subdirectory,
mumble, let me know if you can't find them.
```
