### ISSUE TITLE
combine_output11 error/output naming inconsistency issue

### ISSUE THREAD

**Issue by ZhenlinZhang** [schism-dev/schism#55]
The baroclinic run generates files with naming convention, e.g., local_to_global_000000, and the barotropic run with naming convention, e.g, local_to_global_0000. So this seems to be causing trouble I run combine_output11. I just wonder if this issue has been observed.

**Comment by josephzhang8** [comment]
Most likely you are mixing code/script versions in those runs?

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

From: ZhenlinZhang ***@***.***>
Sent: Monday, February 7, 2022 2:50 PM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] combine_output11 error/output naming inconsistency issue (Issue #55)


[EXTERNAL to VIMS received message]


The baroclinic run generates files with naming convention, e.g., local_to_global_000000, and the barotropic run with naming convention, e.g, local_to_global_0000. So this seems to be causing trouble I run combine_output11. I just wonder if this issue has been observed.

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fissues%2F55&data=04%7C01%7Cyjzhang%40vims.edu%7C80cf04bc30ac4984b29008d9ea730cbb%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637798602121921712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PMkj%2BYNmEkPwgyfB2TCOA0HFACwWEnTn9EwvAlvRp8U%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFBKNZ4ECIC4BZJSEXNUVW3U2AO7FANCNFSM5NYNFQHQ&data=04%7C01%7Cyjzhang%40vims.edu%7C80cf04bc30ac4984b29008d9ea730cbb%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637798602121921712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=s5bX7NAi1XsKv8%2F5LcODXT5eCTcfWZVJj79YZ%2BL1Phg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cyjzhang%40vims.edu%7C80cf04bc30ac4984b29008d9ea730cbb%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637798602121921712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zBVfX5CanMDBSpvXzE1Aqo2cIS65TrdxIRE8R7e9dKU%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cyjzhang%40vims.edu%7C80cf04bc30ac4984b29008d9ea730cbb%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637798602121921712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W3FqvAlsJXnVWC1yIwhxDVBUUpJ6AQr8BC63AmZ32uA%3D&reserved=0>.

**Comment by ZhenlinZhang** [comment]
Thanks for the suggestion! This is no longer an issue.
