### ISSUE TITLE
:wastebasket: Unused files in WWMIII directory?

### ISSUE THREAD

**Issue by jamal919** [schism-dev/schism#58]
Dear All,

While browsing the code-base, I noticed that there are multiple files in WWMIII directory with `_local` suffix. The difference between the non-suffixed and suffixed version seems to be the looping over the nodes. 

Tracking backward in the codebase, it seems that the WWM module used with schism does not contain reference to these files. Yet, they are added in CMakeLists.txt as well as the top-level Makefile.

For further check - I had removed the reference to these `_local` files from CMakeLists.txt and compiled schism-WWM - which went fine.

The files in question are following - 

```
wwm_airsea_local.F90
wwm_ecmwf_local.F90
wwm_femean_local.F90
wwm_femeanws_local.F90
wwm_fkmean_local.F90
wwm_frcutindex_local.F90
wwm_implsch2_local.F90
wwm_implsch_local.F90
wwm_sbottom_local.F90
wwm_sdiss_ardh_vec_local.F90
wwm_sdissip_local.F90
wwm_sinput_ard_local.F90
wwm_sinput_local.F90
wwm_snonlin_local.F90
wwm_st4_local.F90
wwm_st6_local.F90
wwm_stresso_local.F90
wwm_wsigstar_local.F90
```
Additionally, there are some files called `2do`, `forchk_*`, `gap.dat`, `PFMODULE.KEY`, `syserg.bin` that I did not find reference to code. 

Furthermore, there seems to be some leftover runtime files - windbg_0000, wwmdbg_0000, wwmstat_0000 in the folder.

Are these files actually used? If not, then removing these codes might improve the clarity of the code-dir structure.

I am also curious if WWM still compiles by itself, through the makefile inside the WWMIII folder. It looks like the makefiles looks for some `elfe_` dependency which does not exist anymore. 

Thanks.

**Comment by josephzhang8** [comment]
Thx, Jamal for checking these! I've removed those output files. I'll let Aron and other comment on the _local.F90 first before I edit makefiles. Thx.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

From: Jamal Uddin Khan ***@***.***>
Sent: Thursday, February 10, 2022 6:44 AM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] :wastebasket: Unused files in WWM? (Issue #58)


[EXTERNAL to VIMS received message]


Dear All,

While browsing the code-base, I noticed that there are multiple files in WWMIII directory with _local suffix. The difference between the non-suffixed and suffixed version seems to be the looping over the nodes.

Tracking backward in the codebase, it seems that the WWM module used with schism does not contain reference to these files. Yet, they are added in CMakeLists.txt as well as the top-level Makefile.

For further check - I had removed the reference to these _local file from CMakeLists.txt and compiled schism-WWM - which went fine.

The files in question are following -

wwm_airsea_local.F90

wwm_ecmwf_local.F90

wwm_femean_local.F90

wwm_femeanws_local.F90

wwm_fkmean_local.F90

wwm_frcutindex_local.F90

wwm_implsch2_local.F90

wwm_implsch_local.F90

wwm_sbottom_local.F90

wwm_sdiss_ardh_vec_local.F90

wwm_sdissip_local.F90

wwm_sinput_ard_local.F90

wwm_sinput_local.F90

wwm_snonlin_local.F90

wwm_st4_local.F90

wwm_st6_local.F90

wwm_stresso_local.F90

wwm_wsigstar_local.F90

Additionally, there are some files called 2do, forchk_*, gap.dat, PFMODULE.KEY, syserg.bin that I did not find reference to code.

Furthermore, there seems to be some leftover runtime files - windbg_0000, wwmdbg_0000, wwmstat_0000 in the folder.

Are these files actually used? If not, then removing these codes might improve the clarity of the code-dir structure.

I am also curious if WWM still compiles by itself, through the makefile inside the WWMIII folder.

Thanks.

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fissues%2F58&data=04%7C01%7Cyjzhang%40vims.edu%7C0bea5bb549044c8b264508d9ec8a9e1f%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637800902396039595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4u9j4pmT9nKARsBlm7%2FJvAXbrW%2BsLVv7cB8Szw%2FOtxY%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFBKNZ4NLZYDS4PUAYSHZE3U2OQHVANCNFSM5OAOF35Q&data=04%7C01%7Cyjzhang%40vims.edu%7C0bea5bb549044c8b264508d9ec8a9e1f%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637800902396039595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sP73IGABQIbHuuOUOUXbJa4%2FQjnvliLqH7goSIYRIzE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cyjzhang%40vims.edu%7C0bea5bb549044c8b264508d9ec8a9e1f%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637800902396039595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=m5B0Xs1Hmc1aeehv3H5j%2BYNp3mKN6Pzgjnk6SCPds6c%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cyjzhang%40vims.edu%7C0bea5bb549044c8b264508d9ec8a9e1f%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637800902396039595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tsKcrZ0goho4uVRQrvPPuIk%2BbH%2BeM26qa4nZ0%2Ft8ywI%3D&reserved=0>.

**Comment by jamal919** [comment]
Thanks @josephzhang8 , I have created PR #59 for further discussion.
