### ISSUE TITLE
Compilation fails, runs segfault on DRKZ/levante

### ISSUE THREAD

**Issue by platipodium** [schism-dev/schism#61]
From Feb 2022, the dkrz has a new HPC system "Levante".  This thread describes the efforts to get SCHISM working (compile and complete tests)

- We noticed that a cmake build is possible (see below) but leads to a segfaulting executable
- There are issues with `netcdf` through `mamba`

**Comment by platipodium** [comment]
# Loading modules.

We can either use an `openmpi` or an `intelmpi` toolchain, the modules.

## Common modules

```
module load hdf5
module load netcdf-c
module load netcdf-fortran
module load git
module load intel-oneapi-compilers
```

## Openmpi versus intelmpi

```
module load intel-oneapi-mpi
module swap intel-oneapi-mpi openmpi
```

**Comment by platipodium** [comment]
Here's a first cmake fragment for Levante 

```
###DKRZ Levante

set (SCHISM_EXE_BASENAME pschism_LEVANTE CACHE STRING "Base name (modules and file extension to be added of the executable. If you want a machine name, add it here")

###Relative paths won't work
set(CMAKE_Fortran_COMPILER ifort CACHE PATH "Path to serial Fortran compiler")
set(CMAKE_C_COMPILER icc  CACHE PATH "Path to serial Fortran compiler")
#set(NetCDF_FORTRAN_DIR "$ENV{NETCDF_FORTRAN}"  CACHE PATH "Path to NetCDF Fortran library")
#set(NetCDF_C_DIR "$ENV{NETCDF}" CACHE PATH "Path to NetCDF C library")
set(CMAKE_Fortran_FLAGS_RELEASE "-O2 -mcmodel=medium  -mtune=core-avx2" CACHE STRING "Fortran flags" FORCE)

#Compiler flags for openmpi
#set(CMAKE_Fortran_FLAGS_RELEASE "-O2 -mcmodel=medium -assume byterecl" CACHE STRING "Fortran flags" FORCE)
```

**Comment by platipodium** [comment]
I uploaded a makefile fragment `Make.defs.levante.openmpi` that circumvents the messed-up mamba paths introduced by the (needed) `python3` module.

```
NFCONFIG=$(shell module unload python3; which nf-config; module load python3)
NCCONFIG=$(shell module unload python3; which nc-config; module load python3)
$(info $(ENV) uses as for netCDF C config $(NCCONFIG))
$(info $(ENV) uses as for netCDF Fortran config $(NFCONFIG))

CDFLIBS = $(shell $(NFCONFIG) --flibs) $(shell $(NCCONFIG) --libs)
$(info $(ENV) uses netCDF with CDFLIBS=$(CDFLIBS))
CDFMOD = -I$(shell $(NFCONFIG) --includedir)
$(info $(ENV) uses netCDF with CDFMOD=$(CDFMOD))
```

**Comment by josephzhang8** [comment]
Thx to Carsten's magic, we now have a working toolkit (based on gcc) on Levante! Use 

(1) modules.levante in src/Utility/Cluster_files    (you can source modules.levante)
(2) cmake file is SCHISM.local.levante.gcc
(3) batch script is run_levante_ompi   in src/Utility/Cluster_files

That's it. I'm still looking at performance for large core counts.

**Comment by platipodium** [comment]
They installed a new toolchain with `intel`: 

the system administrator has installed the missing libraries on levante. Please try to re-build your application using the following modules:

``
hdf5/1.12.1-intel-oneapi-mpi-2021.5.0-intel-2021.5.0
netcdf-c/4.8.1-intel-oneapi-mpi-2021.5.0-intel-2021.5.0
netcdf-fortran/4.5.3-intel-oneapi-mpi-2021.5.0-intel-2021.5.0
parallel-netcdf/1.12.2-intel-oneapi-mpi-2021.5.0-intel-2021.5.0
```

The path to the shared netCDF-Fortran library can be coded in the binary using the following flag:

`-Wl,-rpath,/sw/spack-levante/netcdf-fortran-4.5.3-r5r3ev/lib/`

**Comment by josephzhang8** [comment]
Will do after Levante is back from maintenance. Thx Carsten.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by josephzhang8** [comment]
I tried those libs but no success.

So far:

  1.  Gcc toolset: working for small cases, but NaN for large case
  2.  Intel: not working, and error suggests some conflicts of MPI versions btw openMPI and netcdf (parallel)

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by platipodium** [comment]
I currently get (with gcc toolchain) 

```
/sw/spack-levante/netcdf-fortran-4.5.3-jlxcfz/lib/libnetcdff.so: undefined reference to `_gfortran_os_error_at@GFORTRAN_10'
```

**Comment by platipodium** [comment]
Solved this by adding the following lines to local CMake config:

```
# To avoid dynamic loading of wrong standard library, force these to static
set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")
```
from https://stackoverflow.com/questions/24648357/compiling-a-static-executable-with-cmake

**Comment by josephzhang8** [comment]
We have updated the module, cmake and batch script files for Levante. At the moment, both Intel and gcc work well for meshes of any size. Intel is faster.

**Comment by josephzhang8** [comment]
Thx Carsten!


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by josephzhang8** [comment]
Issues resolved.
