### ISSUE TITLE
:bug: Compilation problem

### ISSUE THREAD

**Issue by jamal919** [schism-dev/schism#63]
This extra "&" at L135 is causing problem and throwing error of "invalid character. Changing "&&" to "&" solves it.

https://github.com/schism-dev/schism/blob/44dddf2f3e3d2dc86a14637fd70ce0cc1d881921/src/Hydro/schism_step.F90#L136

**Comment by josephzhang8** [comment]
Fixed; thx Jamal!


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

From: Jamal Uddin Khan ***@***.***>
Sent: Sunday, April 3, 2022 1:08 PM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] :bug: Compilation problem (Issue #63)


[EXTERNAL to VIMS received message]


This extra "&" at L135 is causing problem and throwing error of "invalid character.

https://github.com/schism-dev/schism/blob/44dddf2f3e3d2dc86a14637fd70ce0cc1d881921/src/Hydro/schism_step.F90#L136<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fblob%2F44dddf2f3e3d2dc86a14637fd70ce0cc1d881921%2Fsrc%2FHydro%2Fschism_step.F90%23L136&data=04%7C01%7Cyjzhang%40vims.edu%7Cefd03c4a53f442c8e1cf08da15947d20%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637846024747571947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KBpT85XrUma6Of2LTqsESKSz02DSfq1RJrErnOiYYxc%3D&reserved=0>

-
