### ISSUE TITLE
Question about new IO outputs

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [schism-dev/schism#69]
I'm running SCHISM model with PAHM (commit `92ff067`) and I'm using new IO. I'm trying to understand how the output is configured and how to use the output files. I have a few questions:
- In my input `param.in` I don't have any configuations for `IOF_HYDRO` and in `param.nml.out` I see that the the output is 
      ```IOF_HYDRO       =           1, 23*0, 2*1, 14*0```
  Does this mean the elevation and horizontal velocity should be in the output? I'm running tidal + parametric wind model (`nws=-1`)
- For the simulation in the previous item the output is a single `out2d_1.nc` file, and there are no `schout` files. Is this what I should expect?
- This `out2d_1.nc` file has `elevation` variable, but I don't see horizontal velocity in it.

**Comment by josephzhang8** [comment]
Hi Sorrosh:

You can see the sample param.nml in sample/, where you can find the 'default' setting for most parameters. If you did not specify anything for iof_hydro the elev and horizontal vel are turned on (and others off).

In new I/O, all 2D variables share a nc output called out2d_*.nc, whereas each of the 3D variables has its own output. So in your case you should see out2d* and horizontalVel[X,Y]_*.nc (note that vector outputs will have x,y components in separate files).

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

From: Soroosh Mani ***@***.***>
Sent: Thursday, June 9, 2022 12:13 PM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] Question about new IO outputs (Issue #69)


[EXTERNAL to VIMS received message]


I'm running SCHISM model with PAHM (commit 92ff067) and I'm using new IO. I'm trying to understand how the output is configured and how to use the output files. I have a few questions:

  *   In my input param.in I don't have any configuations for IOF_HYDRO and in param.nml.out I see that the the output is
IOF_HYDRO = 1, 23*0, 2*1, 14*0
Does this mean the elevation and horizontal velocity should be in the output? I'm running tidal + parametric wind model (nws=-1)
  *   For the simulation in the previous item the output is a single out2d_1.nc file, and there are no schout files. Is this what I should expect?
  *   This out2d_1.nc file has elevation variable, but I don't see horizontal velocity in it.

-

**Comment by SorooshMani-NOAA** [comment]
Thank you @josephzhang8, I just noticed the two horizontalVel files in the output, thank you for clarifying how the new IO works.
