### ISSUE TITLE
schism build failure with ifort11

### ISSUE THREAD

**Issue by zeekus** [schism-dev/schism#85]
How do I get schism to compile the last 6-10% ? 

repos tried: ISM v2, master, ISM_Balg

Is something too old ? 

cmake version 3.24.1
Intel Fortran 11.0.081
GNU Make 3.82 

Our Cmake run was successful: 
cmake run: /usr/local/bin/cmake -D CMAKE_C_COMPILER=/usr/bin/gcc -D CMAKE_Fortran_COMPILER=/modeling/tools/intel/11.0.081/bin/intel64/ifort -C ../cmake/SCHISM.local.build  -C ../cmake/SCHISM.local.cmake.bora ../src/

But, it appears make is sending some paramaters that the Intel compiler doesn't. Could this be a bug ? 

make: make pschism VERBOSE=1

repo: ISM_Balg

output from: 
[ 94%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_init.F90.o
cd /home/centos/schism/build/Hydro && /modeling/tools/intel/11.0.081/bin/intel64/ifort -DMPIVERSION=2 -DPREC_EVAP -DSCHISM -DTVD_VL -DUSE_ANALYSIS -DUSE_HYDRO -DUSE_SCHISM -I/modeling/tools/intel/compilers_and_libraries_2017.2.174/linux/mpi/intel64/include -I/modeling/tools/lib/netcdf/netcdf-4.4.1.1-intel/include -I/home/centos/schism/build/include -I/modeling/tools/lib/netcdf/netcdf-4.4.1.1-intel/include -O2 -mcmodel=medium -assume byterecl -ipo -axCORE-AVX2 -xSSE4.2 -module ../include -cpp -c /home/centos/schism/src/Hydro/schism_init.F90 -o CMakeFiles/hydro.dir/schism_init.F90.o
ifort: command line warning #10130: unknown extension 'C' ignored in option '-ax'
ifort: command line warning #10130: unknown extension 'R' ignored in option '-ax'
ifort: command line warning #10130: unknown extension 'E' ignored in option '-ax'
ifort: command line warning #10130: unknown extension '-' ignored in option '-ax'
ifort: command line warning #10130: unknown extension 'A' ignored in option '-ax'
ifort: command line warning #10130: unknown extension 'V' ignored in option '-ax'
ifort: command line warning #10130: unknown extension 'X' ignored in option '-ax'
ifort: command line warning #10130: unknown extension '2' ignored in option '-ax'
/home/centos/schism/src/Hydro/schism_init.F90(188): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [LEVEL_AGE]
     &level_age,vclose_surf_frac,iadjust_mass_consv0,ipre2, &
------^
/home/centos/schism/src/Hydro/schism_init.F90(192): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_HYDRO]
     namelist /SCHOUT/nc_out,iof_hydro,iof_wwm,iof_gen,iof_age,iof_sed,iof_eco,iof_icm,iof_cos,iof_fib, &
-----------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(192): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_WWM]
     namelist /SCHOUT/nc_out,iof_hydro,iof_wwm,iof_gen,iof_age,iof_sed,iof_eco,iof_icm,iof_cos,iof_fib, &
---------------------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(192): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_GEN]
     namelist /SCHOUT/nc_out,iof_hydro,iof_wwm,iof_gen,iof_age,iof_sed,iof_eco,iof_icm,iof_cos,iof_fib, &
-----------------------------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(192): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_AGE]
     namelist /SCHOUT/nc_out,iof_hydro,iof_wwm,iof_gen,iof_age,iof_sed,iof_eco,iof_icm,iof_cos,iof_fib, &
-------------------------------------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(192): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_SED]
     namelist /SCHOUT/nc_out,iof_hydro,iof_wwm,iof_gen,iof_age,iof_sed,iof_eco,iof_icm,iof_cos,iof_fib, &
---------------------------------------------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(192): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_ECO]
     namelist /SCHOUT/nc_out,iof_hydro,iof_wwm,iof_gen,iof_age,iof_sed,iof_eco,iof_icm,iof_cos,iof_fib, &
-----------------------------------------------------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(192): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_ICM]
     namelist /SCHOUT/nc_out,iof_hydro,iof_wwm,iof_gen,iof_age,iof_sed,iof_eco,iof_icm,iof_cos,iof_fib, &
-------------------------------------------------------------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(192): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_COS]
     namelist /SCHOUT/nc_out,iof_hydro,iof_wwm,iof_gen,iof_age,iof_sed,iof_eco,iof_icm,iof_cos,iof_fib, &
---------------------------------------------------------------------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(192): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_FIB]
     namelist /SCHOUT/nc_out,iof_hydro,iof_wwm,iof_gen,iof_age,iof_sed,iof_eco,iof_icm,iof_cos,iof_fib, &
-----------------------------------------------------------------------------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(193): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_SED2D]
     &iof_sed2d,iof_ice,iof_ana,iof_marsh,iof_dvd, &
------^
/home/centos/schism/src/Hydro/schism_init.F90(193): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_ICE]
     &iof_sed2d,iof_ice,iof_ana,iof_marsh,iof_dvd, &
----------------^
/home/centos/schism/src/Hydro/schism_init.F90(193): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_ANA]
     &iof_sed2d,iof_ice,iof_ana,iof_marsh,iof_dvd, &
------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(193): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_MARSH]
     &iof_sed2d,iof_ice,iof_ana,iof_marsh,iof_dvd, &
--------------------------------^
/home/centos/schism/src/Hydro/schism_init.F90(193): error #6578: A NAMELIST group object must not be an allocatable object, a pointer, or a variable of a type that has an ultimate component that is a pointer or an allocatable array.   [IOF_DVD]
     &iof_sed2d,iof_ice,iof_ana,iof_marsh,iof_dvd, &
------------------------------------------^
compilation aborted for /home/centos/schism/src/Hydro/schism_init.F90 (code 1)
make[3]: *** [Hydro/CMakeFiles/hydro.dir/schism_init.F90.o] Error 1
make[3]: Leaving directory `/home/centos/schism/build'
make[2]: *** [Hydro/CMakeFiles/hydro.dir/all] Error 2
make[2]: Leaving directory `/home/centos/schism/build'
make[1]: *** [Driver/CMakeFiles/pschism.dir/rule] Error 2
make[1]: Leaving directory `/home/centos/schism/build'
make: *** [pschism] Error 2

**Comment by jamal919** [comment]
Could it be related to the mismatch of gcc and ifort? Have you tried to use icc as the C compiler?

**Comment by zeekus** [comment]
I recompiled everything using gcc and gfortran and seem to get stopped at the same module. The 'hydro' module will not compile. 

[root@ip-myip build]# module list
Currently Loaded Modulefiles:
  1) netcdf-fortran-4.5.4-gcc-4.8.5-damijzt   2) hdf5-1.12.2-gcc-4.8.5-cbshryq            3) openmpi-4.1.4-gcc-4.8.5-fiqiibx
  
  
[root@ip-myip build]# /usr/local/bin/cmake -D CMAKE_C_COMPILER=/usr/bin/gcc -D CMAKE_Fortran_COMPILER=/bin/gfortran -C ../cmake/SCHISM.local.build  -C ../cmake/SCHISM.local.bora.gnu  ../src/
loading initial cache file ../cmake/SCHISM.local.build




--
################   Begin SCHISM Configuration   ################
-- In-source builds not allowed
-- The C compiler identification is GNU 4.8.5
-- The Fortran compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /bin/gfortran - skipped
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--
### Your compiler is /bin/gfortran
--
### No CMAKE_BUILD_TYPE selected in command or cache, default to Release.
Alternatives are Debug and RelWithDebInfo
--
### Processing algorithmic switches and build options involving functionality for main project
-- Build definition tags set to _TVD-VL
--
### Configuring MPI Library
-- Found MPI_C: /root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openmpi-4.1.4-fiqiibxuryj7kahjg7dhtuuirm4fjove/lib/libmpi.so (found version "3.1")
-- Found MPI_CXX: /root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openmpi-4.1.4-fiqiibxuryj7kahjg7dhtuuirm4fjove/lib/libmpi.so (found version "3.1")
-- Found MPI_Fortran: /root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openmpi-4.1.4-fiqiibxuryj7kahjg7dhtuuirm4fjove/lib/libmpi_usempi.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- MPIVERSION = 2
--
### Configuring NetCDF
-- Found NetCDF: /usr/include;/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/netcdf-fortran-4.5.4-damijztptvt6urkr4hdjthkspdsmpcya/include (found version "4.3.3.1") found components: C Fortran
-- FindNetCDF defines targets:
--   - NetCDF_VERSION [4.3.3.1]
--   - NetCDF_PARALLEL [FALSE]
--   - NetCDF_C_CONFIG_EXECUTABLE [/usr/bin/nc-config]
--   - NetCDF::NetCDF_C [SHARED] [Root: /usr] Lib: /usr/lib64/libnetcdf.so
--   - NetCDF_Fortran_CONFIG_EXECUTABLE [/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/netcdf-fortran-4.5.4-damijztptvt6urkr4hdjthkspdsmpcya/bin/nf-config]
--   - NetCDF::NetCDF_Fortran [SHARED] [Root: /root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/netcdf-fortran-4.5.4-damijztptvt6urkr4hdjthkspdsmpcya] Lib: /root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/netcdf-fortran-4.5.4-damijztptvt6urkr4hdjthkspdsmpcya/lib
/libnetcdff.so
--

### Assigning output directories for binaries (bin), modules (include) and libraries (lib)
--
### Adding enabled libraries to project
--
### Configuring ParMETIS
-- Using SCHISM's internal ParMETIS library.
CMake Deprecation Warning at ParMetis-4.0.3/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for getline
-- Looking for getline - found
-- checking for thread-local storage - found
-- PARMETIS_DIR: /home/centos/schism/src/ParMetis-4.0.3
-- PARMETIS_VER: ParMetis-4.0.3
-- hydro_extra_src=
-- Mod libraries:
-- Added Hydro
-- Added Core
--
### Configuring Driver
Using schism module libraries core;hydro
-- START: pschism_BORA_GNU:pschism_BORA_GNU
-- Executable name with this configuration will be pschism_BORA_GNU_TVD-VL
-- All defines:
--
### Configuring Utilities
-- In /Utility NetCDF_LIBS /usr/lib64/libnetcdf.so;/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/netcdf-fortran-4.5.4-damijztptvt6urkr4hdjthkspdsmpcya/lib/libnetcdff.so
-- In /Utility NetCDF_LIBS /usr/lib64/libnetcdf.so;/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/netcdf-fortran-4.5.4-damijztptvt6urkr4hdjthkspdsmpcya/lib/libnetcdff.so
-- In Utility/Gen_Hotstart
-- In Utility/Grid_Scripts
-- Configuring done
-- Generating done
-- Build files have been written to: /home/centos/schism/build

make pschism 

[ 88%] Linking C static library ../../lib/libparmetis.a
cd /home/centos/schism/build/ParMetis-4.0.3/libparmetis && /usr/local/bin/cmake -P CMakeFiles/parmetis.dir/cmake_clean_target.cmake
cd /home/centos/schism/build/ParMetis-4.0.3/libparmetis && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/parmetis.dir/link.txt --verbose=1
/usr/bin/ar qc ../../lib/libparmetis.a CMakeFiles/parmetis.dir/akwayfm.c.o CMakeFiles/parmetis.dir/ametis.c.o CMakeFiles/parmetis.dir/balancemylink.c.o CMakeFiles/parmetis.dir/comm.c.o CMakeFiles/parmetis.dir/csrmatch.c.o CMakeFiles/parmetis.dir/ctrl.c.o CMakeFiles/parmetis.dir/debug.c.o CMakeFiles/parmetis.dir/diffutil.c.o CMakeFiles/parmetis.dir/frename.c.o CMakeFiles/parmetis.dir/gkmetis.c.o CMakeFiles/parmetis.dir/gkmpi.c.o CMakeFiles/parmetis.dir/graph.c.o CMakeFiles/parmetis.dir/initbalance.c.o CMakeFiles/parmetis.dir/initmsection.c.o CMakeFiles/parmetis.dir/initpart.c.o CMakeFiles/parmetis.dir/kmetis.c.o CMakeFiles/parmetis.dir/kwayrefine.c.o CMakeFiles/parmetis.dir/match.c.o CMakeFiles/parmetis.dir/mdiffusion.c.o CMakeFiles/parmetis.dir/mesh.c.o CMakeFiles/parmetis.dir/mmetis.c.o CMakeFiles/parmetis.dir/move.c.o CMakeFiles/parmetis.dir/msetup.c.o CMakeFiles/parmetis.dir/node_refine.c.o CMakeFiles/parmetis.dir/ometis.c.o CMakeFiles/parmetis.dir/pspases.c.o CMakeFiles/parmetis.dir/redomylink.c.o CMakeFiles/parmetis.dir/remap.c.o CMakeFiles/parmetis.dir/renumber.c.o CMakeFiles/parmetis.dir/rmetis.c.o CMakeFiles/parmetis.dir/selectq.c.o CMakeFiles/parmetis.dir/serial.c.o CMakeFiles/parmetis.dir/stat.c.o CMakeFiles/parmetis.dir/timer.c.o CMakeFiles/parmetis.dir/util.c.o CMakeFiles/parmetis.dir/wave.c.o CMakeFiles/parmetis.dir/weird.c.o CMakeFiles/parmetis.dir/wspace.c.o CMakeFiles/parmetis.dir/xyzpart.c.o
/usr/bin/ranlib ../../lib/libparmetis.a
make[3]: Leaving directory `/home/centos/schism/build'
[ 88%] Built target parmetis
make  -f Hydro/CMakeFiles/hydro.dir/build.make Hydro/CMakeFiles/hydro.dir/depend
make[3]: Entering directory `/home/centos/schism/build'
cd /home/centos/schism/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/centos/schism/src /home/centos/schism/src/Hydro /home/centos/schism/build /home/centos/schism/build/Hydro /home/centos/schism/build/Hydro/CMakeFiles/hydro.dir/DependInfo.cmake --color=
make[3]: Leaving directory `/home/centos/schism/build'
make  -f Hydro/CMakeFiles/hydro.dir/build.make Hydro/CMakeFiles/hydro.dir/build
make[3]: Entering directory `/home/centos/schism/build'
[ 88%] Building Fortran object Hydro/CMakeFiles/hydro.dir/sflux_9c.F90.o
cd /home/centos/schism/build/Hydro && /bin/gfortran -DMPIVERSION=2 -DSCHISM -DTVD_VL -DUSE_HYDRO -DUSE_SCHISM -I/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openmpi-4.1.4-fiqiibxuryj7kahjg7dhtuuirm4fjove/include -I/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openmpi-4.1.4-fiqiibxuryj7kahjg7dhtuuirm4fjove/lib -I/usr/include -I/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/netcdf-fortran-4.5.4-damijztptvt6urkr4hdjthkspdsmpcya/include -I/home/centos/schism/build/include -O2 -ffree-line-length-none -static-libgfortran -finit-local-zero -J../include   -pthread -pthread -cpp -c /home/centos/schism/src/Hydro/sflux_9c.F90 -o CMakeFiles/hydro.dir/sflux_9c.F90.o
/usr/local/bin/cmake -E cmake_copy_f90_mod include/netcdf_io.mod Hydro/CMakeFiles/hydro.dir/netcdf_io.mod.stamp GNU
/usr/local/bin/cmake -E touch Hydro/CMakeFiles/hydro.dir/sflux_9c.F90.o.provides.build
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_init.F90.o
cd /home/centos/schism/build/Hydro && /bin/gfortran -DMPIVERSION=2 -DSCHISM -DTVD_VL -DUSE_HYDRO -DUSE_SCHISM -I/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openmpi-4.1.4-fiqiibxuryj7kahjg7dhtuuirm4fjove/include -I/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/openmpi-4.1.4-fiqiibxuryj7kahjg7dhtuuirm4fjove/lib -I/usr/include -I/root/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/netcdf-fortran-4.5.4-damijztptvt6urkr4hdjthkspdsmpcya/include -I/home/centos/schism/build/include -O2 -ffree-line-length-none -static-libgfortran -finit-local-zero -J../include   -pthread -pthread -cpp -c /home/centos/schism/src/Hydro/schism_init.F90 -o CMakeFiles/hydro.dir/schism_init.F90.o
/home/centos/schism/src/Hydro/schism_init.F90:503.24:

      read(15,nml=SCHOUT)
                        1
Error: Symbol 'schout' at (1) must be a NAMELIST group name
/home/centos/schism/src/Hydro/schism_init.F90:527.27:

        write(15,nml=SCHOUT)
                           1
Error: Symbol 'schout' at (1) must be a NAMELIST group name
make[3]: *** [Hydro/CMakeFiles/hydro.dir/schism_init.F90.o] Error 1
make[3]: Leaving directory `/home/centos/schism/build'
make[2]: *** [Hydro/CMakeFiles/hydro.dir/all] Error 2
make[2]: Leaving directory `/home/centos/schism/build'
make[1]: *** [Driver/CMakeFiles/pschism.dir/rule] Error 2
make[1]: Leaving directory `/home/centos/schism/build'
make: *** [pschism] Error 2

**Comment by zeekus** [comment]
I downloaded the lastet version of Schism and it appears to got to 100% but failed at the last step. What would cause this ? 

/home/centos/schism/src/ParMetis-4.0.3/libparmetis/wave.c: In function ‘libparmetis__WavefrontDiffusion’:
/home/centos/schism/src/ParMetis-4.0.3/libparmetis/wave.c:253:1: warning: label ‘CleanUpAndExit’ defined but not used [-Wunused-label]
 CleanUpAndExit:
 ^
[ 84%] Building C object ParMetis-4.0.3/libparmetis/CMakeFiles/parmetis.dir/weird.c.o
[ 86%] Building C object ParMetis-4.0.3/libparmetis/CMakeFiles/parmetis.dir/wspace.c.o
[ 86%] Building C object ParMetis-4.0.3/libparmetis/CMakeFiles/parmetis.dir/xyzpart.c.o
[ 88%] Linking C static library ../../lib/libparmetis.a
[ 88%] Built target parmetis
[ 88%] Building Fortran object Hydro/CMakeFiles/hydro.dir/sflux_9c.F90.o
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_init.F90.o
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_step.F90.o
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_finalize.F90.o
[ 92%] Building Fortran object Hydro/CMakeFiles/hydro.dir/bktrk_subs.F90.o
[ 92%] Building Fortran object Hydro/CMakeFiles/hydro.dir/grid_subs.F90.o
[ 94%] Building Fortran object Hydro/CMakeFiles/hydro.dir/lap.F90.o
[ 94%] Building Fortran object Hydro/CMakeFiles/hydro.dir/misc_subs.F90.o
[ 96%] Building Fortran object Hydro/CMakeFiles/hydro.dir/solver_subs.F90.o
[ 96%] Building Fortran object Hydro/CMakeFiles/hydro.dir/transport_TVD.F90.o
[ 98%] Building Fortran object Hydro/CMakeFiles/hydro.dir/transport_TVD_imp.F90.o
[ 98%] Linking Fortran static library ../lib/libhydro.a
[ 98%] Built target hydro
[100%] Building Fortran object Driver/CMakeFiles/pschism.dir/schism_driver.F90.o
[100%] Linking Fortran executable ../bin/pschism_BORA_GNU_TVD-VL
/bin/ld: cannot find -lgfortran
/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make[3]: *** [bin/pschism_BORA_GNU_TVD-VL] Error 1
make[2]: *** [Driver/CMakeFiles/pschism.dir/all] Error 2
make[1]: *** [Driver/CMakeFiles/pschism.dir/rule] Error 2
make: *** [pschism] Error 2

**Comment by josephzhang8** [comment]
Looks like you invoked gfortran somehow and its lib has issues.

**Comment by zeekus** [comment]
It appears the gcc libraries for gfortran where missing on your Centos7 box.

I had to install the 'libgfortran-static' library to get the 'make pschism' command to finish. 

```
[centos@machine build]$ rpm -qal libgfortran-static
/usr/lib/gcc
/usr/lib/gcc/x86_64-redhat-linux
/usr/lib/gcc/x86_64-redhat-linux/4.8.2
/usr/lib/gcc/x86_64-redhat-linux/4.8.2/libgfortran.a
/usr/lib/gcc/x86_64-redhat-linux/4.8.5
```


Before:

``` 
/opt/schism/src/ParMetis-4.0.3/libparmetis/wave.c:253:1: warning: label ‘CleanUpAndExit’ defined but not used [-Wunused-label]
 CleanUpAndExit:
 ^
[ 84%] Building C object ParMetis-4.0.3/libparmetis/CMakeFiles/parmetis.dir/weird.c.o
[ 86%] Building C object ParMetis-4.0.3/libparmetis/CMakeFiles/parmetis.dir/wspace.c.o
[ 86%] Building C object ParMetis-4.0.3/libparmetis/CMakeFiles/parmetis.dir/xyzpart.c.o
[ 88%] Linking C static library ../../lib/libparmetis.a
[ 88%] Built target parmetis
[ 88%] Building Fortran object Hydro/CMakeFiles/hydro.dir/sflux_9c.F90.o
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_init.F90.o
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_step.F90.o
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_finalize.F90.o
[ 92%] Building Fortran object Hydro/CMakeFiles/hydro.dir/bktrk_subs.F90.o
[ 92%] Building Fortran object Hydro/CMakeFiles/hydro.dir/grid_subs.F90.o
[ 94%] Building Fortran object Hydro/CMakeFiles/hydro.dir/lap.F90.o
[ 94%] Building Fortran object Hydro/CMakeFiles/hydro.dir/misc_subs.F90.o
[ 96%] Building Fortran object Hydro/CMakeFiles/hydro.dir/solver_subs.F90.o
[ 96%] Building Fortran object Hydro/CMakeFiles/hydro.dir/transport_TVD.F90.o
[ 98%] Building Fortran object Hydro/CMakeFiles/hydro.dir/transport_TVD_imp.F90.o
[ 98%] Linking Fortran static library ../lib/libhydro.a
[ 98%] Built target hydro
[100%] Building Fortran object Driver/CMakeFiles/pschism.dir/schism_driver.F90.o
[100%] Linking Fortran executable ../bin/pschism_BORA_GNU_TVD-VL
/usr/bin/ld: cannot find -lgfortran
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make[3]: *** [bin/pschism_BORA_GNU_TVD-VL] Error 1
make[2]: *** [Driver/CMakeFiles/pschism.dir/all] Error 2
make[1]: *** [Driver/CMakeFiles/pschism.dir/rule] Error 2
make: *** [pschism] Error 2
```

After installing the missing library: 

```
/opt/schism/src/ParMetis-4.0.3/libparmetis/wave.c: In function ‘libparmetis__WavefrontDiffusion’:
/opt/schism/src/ParMetis-4.0.3/libparmetis/wave.c:253:1: warning: label ‘CleanUpAndExit’ defined but not used [-Wunused-label]
 CleanUpAndExit:
 ^
[ 84%] Building C object ParMetis-4.0.3/libparmetis/CMakeFiles/parmetis.dir/weird.c.o
[ 86%] Building C object ParMetis-4.0.3/libparmetis/CMakeFiles/parmetis.dir/wspace.c.o
[ 86%] Building C object ParMetis-4.0.3/libparmetis/CMakeFiles/parmetis.dir/xyzpart.c.o
[ 88%] Linking C static library ../../lib/libparmetis.a
[ 88%] Built target parmetis
[ 88%] Building Fortran object Hydro/CMakeFiles/hydro.dir/sflux_9c.F90.o
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_init.F90.o
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_step.F90.o
[ 90%] Building Fortran object Hydro/CMakeFiles/hydro.dir/schism_finalize.F90.o
[ 92%] Building Fortran object Hydro/CMakeFiles/hydro.dir/bktrk_subs.F90.o
[ 92%] Building Fortran object Hydro/CMakeFiles/hydro.dir/grid_subs.F90.o
[ 94%] Building Fortran object Hydro/CMakeFiles/hydro.dir/lap.F90.o
[ 94%] Building Fortran object Hydro/CMakeFiles/hydro.dir/misc_subs.F90.o
[ 96%] Building Fortran object Hydro/CMakeFiles/hydro.dir/solver_subs.F90.o
[ 96%] Building Fortran object Hydro/CMakeFiles/hydro.dir/transport_TVD.F90.o
[ 98%] Building Fortran object Hydro/CMakeFiles/hydro.dir/transport_TVD_imp.F90.o
[ 98%] Linking Fortran static library ../lib/libhydro.a
[ 98%] Built target hydro
[100%] Building Fortran object Driver/CMakeFiles/pschism.dir/schism_driver.F90.o
[100%] Linking Fortran executabl
```
