### ISSUE TITLE
Tracer method in 5.10.1

### ISSUE THREAD

**Issue by brey** [schism-dev/schism#93]
I am running a pure hydro model with no tracers. I have always used `itr_met` = 1. 

With 5.10.1 I get

```fortran
Unknown tracer method           1
```

**Comment by josephzhang8** [comment]
Hi George:

Happy New Year!

Yes I've removed explicit transport solver (itr_met=1,2) in the newer versions as the latter are poorly utilized and not well developed anymore; you can use the default itr_met=3. If you use baotropic config you do not need to provide tvd.prop.

Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)
SCHISM web: http://ccrm.vims.edu/schism/
From: George Breyiannis ***@***.***>
Sent: Sunday, January 15, 2023 5:40 AM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] Tracer method in 5.10.1 (Issue #93)


[EXTERNAL to VIMS received message]


I am running a pure hydro model with no tracers. I have always used itr_met = 1.

With 5.10.1 I get

Unknown tracer method           1

-

**Comment by brey** [comment]
Hi @josephzhang8. Happy new Year and all the best.

I see. In fact the use was that in the default `param.nml` I had `ibtp`=1 which now should be `ibtp`=0 to avoid the `tvd.prop` requirement (If I read the manual right).

**Comment by josephzhang8** [comment]
Yes your understanding is correct. Even with b-tropic config you can still have tracer transport invoked and in that case you'l need tvd.prop.


Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)
SCHISM web: http://ccrm.vims.edu/schism/

**Comment by brey** [comment]
Thanks Joseph. I am closing the issue.
