### ISSUE TITLE
Parallelization error - No output files

### ISSUE THREAD

**Issue by simwes** [schism-dev/schism#94]
According to the [tutorial](https://schism-dev.github.io/schism/master/getting-started/running-model.html) in order to run the model there are 2 options:
```
1. mpirun -np NPROC ./pschism <# scribes> if OLDIO is OFF
2. mpirun -np NPROC ./pschism if OLDIO is ON
```
My PC (Ubuntu) has 6 cores (12 CPUs). So if I use the first option, e.g.  `mpirun -np 6 ./pschism 3`  it seems running but it does not produce output!. While if I use the second option, say,  `mpirun -np 6 ./pschism` then 5 of the 6 cores fail with and only one CPU running. I get the following error from each of the failing CPUs:

```
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
   0: ABORT: fill_nc_header: time dim
--------------------------------------------------------------------------
```
It must be something with the parallelization. Thank you for your help!

**Comment by jreniel** [comment]
Hi Simone,
I figured out a recipe that works for Ubuntu 22.04.

First the pre-requisites:

```bash
sudo apt-get install gcc g++ gfortran make cmake netcdf-bin libnetcdf-dev libnetcdff-dev git openmpi-bin libopenmpi-dev
```

You may also need a python installation if it complains about not finding python:
```bash
sudo apt-get install python2-minimal
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
```

Now let's do a fresh clone (just for clarity):

```bash
git clone https://github.com/schism-dev/schism
cd schism
mkdir build
cd build
```

Now for the magic conjuration:
```bash
cmake ../src -DNetCDF_Fortran_LIBRARY=$(nc-config --libdir)/lib^Ctcdff.so -DNetCDF_C_LIBRARY=$(nc-config --libdir)/libnetcdf.so -DNetCDF_INCLUDE_DIR=$(nc-config --prefix)/include -DOLDIO=true -DCMAKE_Fortran_FLAGS_RELEASE="-O2 -ffree-line-length-none -fallow-argument-mismatch"
```
What's magical about this line is that the `openmpi-bin` and `openmpi-dev` libraries that Ubuntu uses are a bit "outdated", and needs the `-DCMAKE_Fortran_FLAGS_RELEASE` flags to work properly.

To execute, make sure you use as launch command `mpiexec -n 6 pschism_OLDIO_TVD-VL`.

Let me know if this works.

-J.

**Comment by simwes** [comment]
It worked!
Thank you very much!
